---
# reference: https://cirrus-ci.org/guide/writing-tasks/

container:
  cpu: 1
  memory: "2G"

# Sanity checks
lint_markdown_task:
  name: "Lint Markdown"
  container:
    image: "docker.io/library/node:latest"
  install_script: "npm install -g markdownlint-cli"
  lint_script: "markdownlint **/*.md"

lint_yaml_task:
  name: "Lint YAML"
  container:
    image: "docker.io/library/alpine:latest"
  install_script: "apk update && apk add yamllint"
  lint_script: "yamllint ."

test_pages_task:
  name: "Test pages"
  container:
    image: "docker.io/library/python:3"
  install_script: "pip install --upgrade -r requirements.txt"
  build_script: "mkdocs build --strict"

deploy_pages_task:
  name: "Test pages"
  only_if: "$CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH &&
            $CIRRUS_TAG != '' &&
            $CIRRUS_ENVIRONMENT != 'CLI'"
  epends_on:
    - "Lint Markdown"
    - "Lint YAML"
    - "Test Pages"
  container:
    image: "docker.io/library/python:3"
  install_script: "pip install --upgrade -r requirements.txt"
  build_script: "mkdocs build --strict"
  deploy_script: "mkdocs gh-deploy --force"
...
