---
# reference: https://www.mkdocs.org/

site_url: "https://docs.while-true-do.io"
site_name: "docs.while-true-do.io"
site_description: "while-true-do.io Documentation"
site_author: "while-true-do.io"
copyright: "&copy 2022 - while-true-do.io"

repo_url: "https://github.com/whiletruedoio/.github/"
repo_name: "GitHub"

edit_uri: "edit/main/docs/"

extra_css:
  - "stylesheets/extra.css"

theme:
  logo: "assets/logo/whiletruedoio_logo_light_round.png"
  favicon: "assets/logo/favicon.png"
  name: "material"
  highlightjs: true
  titles_only: true
  features:
    - "navigation.instant"
    - "navigation.tracking"
    - "navigation.top"
  palette:
    - scheme: "default"
      primary: "teal"
      toggle:
        icon: "material/toggle-switch-variant"
        name: "Switch to dark mode"
    - scheme: "slate"
      primary: "teal"
      toggle:
        icon: "material/toggle-switch-variant-off"
        name: "Switch to light mode"

markdown_extensions:
  - "meta"
  - "attr_list"
  - "pymdownx.betterem"
  - "pymdownx.emoji"

plugins:
  - "search"
  - "pdf-export"

extra:
  generator: false
  social:
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/whiletruedoio"
      name: "while-true-do.io on Twitter"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/whiletruedoio"
      name: "while-true-do.io on GitHub"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/whiletruedoio"
      name: "while-true-do.io on LinkedIn"
    - icon: "fontawesome/brands/docker"
      link: "https://hub.docker.com/u/whiletruedoio"
      name: "while-true-do.io on Docker Hub"
    - icon: "fontawesome/solid/comments"
      link: "https://matrix.to/#/#whiletruedoio-community:matrix.org"
      name: "while-true-do.io on Matrix"
...
