---
# Reference: https://docs.github.com/en/communities

blank_issues_enabled: false

contact_links:

  - name: "Chat"
    url: "https://matrix.to/#/#whiletruedoio-community:matrix.org"
    about: "I want to chat via Matrix."

  - name: "Mail"
    url: "https://mailxto.com/qzrtnj"
    about: "I want to send a mail."
...
